### ISSUE TITLE
Fix Configuration Files Not Found - Complete Setup Guide

### ISSUE THREAD

**Issue by niraj045** [niraj045/ChatWave#5]
## 🔧 Fix: Configuration Files Not Found - Setup Working Test Environment

The error shows that configuration files are not found because they need to be created in the proper directory structure. Let me provide the complete setup.

## 📁 Directory Structure Setup

Create this exact directory structure in your project:

```
src/
├── main/
│   ├── java/
│   │   └── org/appops/amur/config/
│   │       ├── ConfigLoader.java
│   │       ├── EnvironmentConfigStore.java
│   │       ├── CoreServiceConfig.java
│   │       ├── SlimServiceConfig.java
│   │       └── ImplServiceConfig.java
│   └── resources/
│       └── env-config/
│           ├── core.yml
│           ├── TestService/
│           │   └── slim.yml
│           ├── HService/
│           │   └── slim.yml
│           ├── UserService/
│           │   └── slim.yml
│           ├── SomeOtherService/
│           │   └── slim.yml
│           └── NirajService/
│               ├── slim.yml
│               └── impl.yml
└── test/
    ├── java/
    │   └── org/appops/amur/config/
    │       ├── ConfigLoaderTest.java
    │       ├── EnvironmentConfigStoreTest.java
    │       ├── UserServiceConfig.java
    │       ├── EmailServiceConfig.java
    │       ├── AuthServiceConfig.java
    │       └── PaymentServiceConfig.java
    └── resources/
        └── env-config/
            ├── core.yml
            ├── TestService/
            │   └── slim.yml
            ├── HService/
            │   └── slim.yml
            ├── UserService/
            │   └── slim.yml
            ├── SomeOtherService/
            │   └── slim.yml
            └── NirajService/
                ├── slim.yml
                └── impl.yml
```

### 1. src/main/resources/env-config/core.yml

```yaml
serviceName: "CoreService"
webappDirectory: "/webapp"
gatewayUrl: "http://localhost:8080"
annotationClass: "org.appops.annotations.Service"
executionMode: "development"
jettyConfig:
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:testdb"
  user: "sa"
  password: "password"
  sessionTimeout: 1800
  maxConnections: 100
```

### 2. src/main/resources/env-config/TestService/slim.yml

```yaml
config:
  UserServiceConfig:
    baseUrl: "http://localhost:8081"
    apiVersion: "v1"
    timeout: 5000
    retryCount: 3
  EmailServiceConfig:
    smtpHost: "smtp.gmail.com"
    smtpPort: 587
    senderEmail: "test@example.com"
    enableTLS: true
```

### 3. src/main/resources/env-config/HService/slim.yml

```yaml
config:
  DatabaseConfig:
    host: "localhost"
    port: 5432
    database: "hservice_db"
    username: "huser"
    password: "hpassword"
  CacheConfig:
    redisHost: "localhost"
    redisPort: 6379
    ttl: 3600
```

### 4. src/main/resources/env-config/UserService/slim.yml

```yaml
config:
  UserManagementConfig:
    userRegistrationEnabled: true
    maxLoginAttempts: 3
    passwordExpiryDays: 90
    enableTwoFactor: false
```

### 5. src/main/resources/env-config/SomeOtherService/slim.yml

```yaml
config:
  LoggingConfig:
    logLevel: "INFO"
    logToFile: true
    maxFileSize: "10MB"
    retentionDays: 30
```

### 6. src/main/resources/env-config/NirajService/slim.yml

```yaml
config:
  AuthServiceConfig:
    authUrl: "http://localhost:8082/auth"
    tokenExpiry: 3600
    secretKey: "mySecretKey123"
  NotificationConfig:
    enableEmail: true
    enableSMS: false
    defaultTemplate: "default.html"
```

### 7. src/main/resources/env-config/NirajService/impl.yml

```yaml
config:
  PaymentServiceConfig:
    paymentGateway: "stripe"
    apiKey: "sk_test_123456"
    webhookSecret: "whsec_123456"
    currency: "USD"
  OrderServiceConfig:
    maxOrderItems: 10
    orderTimeout: 1800
    autoConfirm: true
```

### 1. UserServiceConfig.java

```java
package org.appops.amur.config;

public class UserServiceConfig {
    private String baseUrl;
    private String apiVersion;
    private int timeout;
    private int retryCount;

    public UserServiceConfig() {}

    // Getters and Setters
    public String getBaseUrl() { return baseUrl; }
    public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }

    public String getApiVersion() { return apiVersion; }
    public void setApiVersion(String apiVersion) { this.apiVersion = apiVersion; }

    public int getTimeout() { return timeout; }
    public void setTimeout(int timeout) { this.timeout = timeout; }

    public int getRetryCount() { return retryCount; }
    public void setRetryCount(int retryCount) { this.retryCount = retryCount; }

    @Override
    public String toString() {
        return String.format("UserServiceConfig{baseUrl='%s', apiVersion='%s', timeout=%d, retryCount=%d}",
                baseUrl, apiVersion, timeout, retryCount);
    }
}
```

### 2. EmailServiceConfig.java

```java
package org.appops.amur.config;

public class EmailServiceConfig {
    private String smtpHost;
    private int smtpPort;
    private String senderEmail;
    private boolean enableTLS;

    public EmailServiceConfig() {}

    public String getSmtpHost() { return smtpHost; }
    public void setSmtpHost(String smtpHost) { this.smtpHost = smtpHost; }

    public int getSmtpPort() { return smtpPort; }
    public void setSmtpPort(int smtpPort) { this.smtpPort = smtpPort; }

    public String getSenderEmail() { return senderEmail; }
    public void setSenderEmail(String senderEmail) { this.senderEmail = senderEmail; }

    public boolean isEnableTLS() { return enableTLS; }
    public void setEnableTLS(boolean enableTLS) { this.enableTLS = enableTLS; }

    @Override
    public String toString() {
        return String.format("EmailServiceConfig{smtpHost='%s', smtpPort=%d, senderEmail='%s', enableTLS=%s}",
                smtpHost, smtpPort, senderEmail, enableTLS);
    }
}
```

### 3. AuthServiceConfig.java

```java
package org.appops.amur.config;

public class AuthServiceConfig {
    private String authUrl;
    private int tokenExpiry;
    private String secretKey;

    public AuthServiceConfig() {}

    public String getAuthUrl() { return authUrl; }
    public void setAuthUrl(String authUrl) { this.authUrl = authUrl; }

    public int getTokenExpiry() { return tokenExpiry; }
    public void setTokenExpiry(int tokenExpiry) { this.tokenExpiry = tokenExpiry; }

    public String getSecretKey() { return secretKey; }
    public void setSecretKey(String secretKey) { this.secretKey = secretKey; }

    @Override
    public String toString() {
        return String.format("AuthServiceConfig{authUrl='%s', tokenExpiry=%d, secretKey='***'}",
                authUrl, tokenExpiry);
    }
}
```

### 4. PaymentServiceConfig.java

```java
package org.appops.amur.config;

public class PaymentServiceConfig {
    private String paymentGateway;
    private String apiKey;
    private String webhookSecret;
    private String currency;

    public PaymentServiceConfig() {}

    public String getPaymentGateway() { return paymentGateway; }
    public void setPaymentGateway(String paymentGateway) { this.paymentGateway = paymentGateway; }

    public String getApiKey() { return apiKey; }
    public void setApiKey(String apiKey) { this.apiKey = apiKey; }

    public String getWebhookSecret() { return webhookSecret; }
    public void setWebhookSecret(String webhookSecret) { this.webhookSecret = webhookSecret; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    @Override
    public String toString() {
        return String.format("PaymentServiceConfig{paymentGateway='%s', currency='%s'}",
                paymentGateway, currency);
    }
}
```

### 5. NotificationConfig.java

```java
package org.appops.amur.config;

public class NotificationConfig {
    private boolean enableEmail;
    private boolean enableSMS;
    private String defaultTemplate;

    public NotificationConfig() {}

    public boolean isEnableEmail() { return enableEmail; }
    public void setEnableEmail(boolean enableEmail) { this.enableEmail = enableEmail; }

    public boolean isEnableSMS() { return enableSMS; }
    public void setEnableSMS(boolean enableSMS) { this.enableSMS = enableSMS; }

    public String getDefaultTemplate() { return defaultTemplate; }
    public void setDefaultTemplate(String defaultTemplate) { this.defaultTemplate = defaultTemplate; }

    @Override
    public String toString() {
        return String.format("NotificationConfig{enableEmail=%s, enableSMS=%s, defaultTemplate='%s'}",
                enableEmail, enableSMS, defaultTemplate);
    }
}
```

## 🧪 Simple Test Runner

```java
package org.appops.amur.config;

public class ConfigTestRunner {
    public static void main(String[] args) {
        System.out.println("🚀 Testing ConfigLoader with Real Files");
        System.out.println("=======================================");
        
        try {
            // Create ConfigLoader
            ConfigLoader configLoader = new ConfigLoader("NirajService");
            
            // Test individual loads first
            System.out.println("\n1️⃣ Testing Core Config:");
            CoreServiceConfig coreConfig = configLoader.loadCoreConfig();
            if (coreConfig != null) {
                System.out.println("✅ Core Config loaded: " + coreConfig.getServiceName());
            } else {
                System.out.println("❌ Core Config failed to load");
            }
            
            System.out.println("\n2️⃣ Testing TestService Slim Config:");
            SlimServiceConfig testConfig = configLoader.loadSlimConfig("TestService");
            if (testConfig != null) {
                System.out.println("✅ TestService Config loaded with " + 
                                 testConfig.getConfig().size() + " nested configs");
                
                // Check if conversion worked
                Object userConfigObj = testConfig.getConfig().get("UserServiceConfig");
                if (userConfigObj instanceof UserServiceConfig) {
                    UserServiceConfig userConfig = (UserServiceConfig) userConfigObj;
                    System.out.println("   ✅ UserServiceConfig converted: " + userConfig.getBaseUrl());
                }
            } else {
                System.out.println("❌ TestService Config failed to load");
            }
            
            System.out.println("\n3️⃣ Testing NirajService Configs:");
            SlimServiceConfig nirajSlim = configLoader.loadSlimConfig("NirajService");
            if (nirajSlim != null) {
                System.out.println("✅ NirajService Slim Config loaded");
                
                Object authConfigObj = nirajSlim.getConfig().get("AuthServiceConfig");
                if (authConfigObj instanceof AuthServiceConfig) {
                    AuthServiceConfig authConfig = (AuthServiceConfig) authConfigObj;
                    System.out.println("   ✅ AuthServiceConfig converted: " + authConfig.getAuthUrl());
                }
            }
            
            ImplServiceConfig nirajImpl = configLoader.loadImplConfig("NirajService");
            if (nirajImpl != null) {
                System.out.println("✅ NirajService Impl Config loaded");
                
                Object paymentConfigObj = nirajImpl.getConfig().get("PaymentServiceConfig");
                if (paymentConfigObj instanceof PaymentServiceConfig) {
                    PaymentServiceConfig paymentConfig = (PaymentServiceConfig) paymentConfigObj;
                    System.out.println("   ✅ PaymentServiceConfig converted: " + paymentConfig.getPaymentGateway());
                }
            }
            
            System.out.println("\n4️⃣ Testing Full Environment Load:");
            configLoader.loadEnvironmentConfiguration();
            
            EnvironmentConfigStore store = configLoader.getEnvironmentStore();
            System.out.println("\n📊 Final Summary:");
            System.out.println(store.getEnvironmentSummary());
            
        } catch (Exception e) {
            System.err.println("❌ Error during testing: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
```

## 🎯 Expected Success Output

After creating the files, you should see:

```
🚀 Testing ConfigLoader with Real Files
=======================================

1️⃣ Testing Core Config:
🔍 Loading config from: /env-config/core.yml
✅ Successfully loaded Core config for Core
✅ Core config stored
✅ Core Config loaded: CoreService

2️⃣ Testing TestService Slim Config:
🔍 Loading config from: /env-config/TestService/slim.yml
✅ Converted UserServiceConfig to typed object
✅ Converted EmailServiceConfig to typed object
✅ Successfully loaded slim config for TestService
✅ Dependent service stored: TestService
✅ TestService Config loaded with 2 nested configs
   ✅ UserServiceConfig converted: http://localhost:8081

3️⃣ Testing NirajService Configs:
🔍 Loading config from: /env-config/NirajService/slim.yml
✅ Converted AuthServiceConfig to typed object
✅ Converted NotificationConfig to typed object
✅ Successfully loaded slim config for NirajService
✅ Current service slim config stored
✅ NirajService Slim Config loaded
   ✅ AuthServiceConfig converted: http://localhost:8082/auth

🔍 Loading config from: /env-config/NirajService/impl.yml
✅ Converted PaymentServiceConfig to typed object
✅ Converted OrderServiceConfig to typed object
✅ Successfully loaded impl config for NirajService
✅ Current service impl config stored
✅ NirajService Impl Config loaded
   ✅ PaymentServiceConfig converted: stripe
```

## 🔧 Quick Setup Commands

If you're using Maven, create the directories:

```bash
mkdir -p src/main/resources/env-config/TestService
mkdir -p src/main/resources/env-config/HService
mkdir -p src/main/resources/env-config/UserService
mkdir -p src/main/resources/env-config/SomeOtherService
mkdir -p src/main/resources/env-config/NirajService
```

Then create each YAML file in the appropriate directory with the content provided above.

After setting up all files, run your ConfigTestRunner and you should see successful loading of all configurations! 🎉
