### ISSUE TITLE
Fix Path Issues and Create Missing Configuration Files

### ISSUE THREAD

**Issue by niraj045** [niraj045/ChatWave#6]
## 🔧 Fix: Path Issues and Missing Files Setup

Based on your output, there are two main issues:
1. Typo: `test/resorces` should be `test/resources` 
2. Inconsistent path resolution

### Step 1: Create the correct directory structure

```bash
# Navigate to your project root
mkdir -p src/main/resources/env-config/TestService
mkdir -p src/main/resources/env-config/HService  
mkdir -p src/main/resources/env-config/UserService
mkdir -p src/main/resources/env-config/SomeOtherService
mkdir -p src/main/resources/env-config/NirajService

# Also create test resources (if running tests)
mkdir -p src/test/resources/env-config/TestService
mkdir -p src/test/resources/env-config/HService
mkdir -p src/test/resources/env-config/UserService  
mkdir -p src/test/resources/env-config/SomeOtherService
mkdir -p src/test/resources/env-config/NirajService
```

### Step 2: Create core.yml

```yaml
# src/main/resources/env-config/core.yml
serviceName: "CoreService"
webappDirectory: "/webapp"
gatewayUrl: "http://localhost:8080"
annotationClass: "org.appops.annotations.Service"
executionMode: "development"
jettyConfig:
  driver: "org.h2.Driver"
  url: "jdbc:h2:mem:testdb"
  user: "sa"
  password: "password"
  sessionTimeout: 1800
  maxConnections: 100
```

### Step 3: Create TestService/slim.yml

```yaml
# src/main/resources/env-config/TestService/slim.yml
config:
  UserServiceConfig:
    baseUrl: "http://localhost:8081"
    apiVersion: "v1"
    timeout: 5000
    retryCount: 3
  EmailServiceConfig:
    smtpHost: "smtp.gmail.com"
    smtpPort: 587
    senderEmail: "test@example.com"
    enableTLS: true
```

### Step 4: Create HService/slim.yml

```yaml
# src/main/resources/env-config/HService/slim.yml
config:
  DatabaseConfig:
    host: "localhost"
    port: 5432
    database: "hservice_db"
    username: "huser"
    password: "hpassword"
  CacheConfig:
    redisHost: "localhost"
    redisPort: 6379
    ttl: 3600
```

### Step 5: Create UserService/slim.yml

```yaml
# src/main/resources/env-config/UserService/slim.yml
config:
  UserManagementConfig:
    userRegistrationEnabled: true
    maxLoginAttempts: 3
    passwordExpiryDays: 90
    enableTwoFactor: false
```

### Step 6: Create SomeOtherService/slim.yml

```yaml
# src/main/resources/env-config/SomeOtherService/slim.yml
config:
  LoggingConfig:
    logLevel: "INFO"
    logToFile: true
    maxFileSize: "10MB"
    retentionDays: 30
```

### Step 7: Create NirajService/slim.yml

```yaml
# src/main/resources/env-config/NirajService/slim.yml
config:
  AuthServiceConfig:
    authUrl: "http://localhost:8082/auth"
    tokenExpiry: 3600
    secretKey: "mySecretKey123"
  NotificationConfig:
    enableEmail: true
    enableSMS: false
    defaultTemplate: "default.html"
```

### Step 8: Create NirajService/impl.yml

```yaml
# src/main/resources/env-config/NirajService/impl.yml
config:
  PaymentServiceConfig:
    paymentGateway: "stripe"
    apiKey: "sk_test_123456"
    webhookSecret: "whsec_123456"
    currency: "USD"
  OrderServiceConfig:
    maxOrderItems: 10
    orderTimeout: 1800
    autoConfirm: true
```

### 1. UserServiceConfig.java

```java
package org.appops.amur.config;

public class UserServiceConfig {
    private String baseUrl;
    private String apiVersion;
    private int timeout;
    private int retryCount;

    public UserServiceConfig() {}

    public String getBaseUrl() { return baseUrl; }
    public void setBaseUrl(String baseUrl) { this.baseUrl = baseUrl; }

    public String getApiVersion() { return apiVersion; }
    public void setApiVersion(String apiVersion) { this.apiVersion = apiVersion; }

    public int getTimeout() { return timeout; }
    public void setTimeout(int timeout) { this.timeout = timeout; }

    public int getRetryCount() { return retryCount; }
    public void setRetryCount(int retryCount) { this.retryCount = retryCount; }

    @Override
    public String toString() {
        return String.format("UserServiceConfig{baseUrl='%s', apiVersion='%s', timeout=%d, retryCount=%d}",
                baseUrl, apiVersion, timeout, retryCount);
    }
}
```

### 2. EmailServiceConfig.java

```java
package org.appops.amur.config;

public class EmailServiceConfig {
    private String smtpHost;
    private int smtpPort;
    private String senderEmail;
    private boolean enableTLS;

    public EmailServiceConfig() {}

    public String getSmtpHost() { return smtpHost; }
    public void setSmtpHost(String smtpHost) { this.smtpHost = smtpHost; }

    public int getSmtpPort() { return smtpPort; }
    public void setSmtpPort(int smtpPort) { this.smtpPort = smtpPort; }

    public String getSenderEmail() { return senderEmail; }
    public void setSenderEmail(String senderEmail) { this.senderEmail = senderEmail; }

    public boolean isEnableTLS() { return enableTLS; }
    public void setEnableTLS(boolean enableTLS) { this.enableTLS = enableTLS; }

    @Override
    public String toString() {
        return String.format("EmailServiceConfig{smtpHost='%s', smtpPort=%d, senderEmail='%s', enableTLS=%s}",
                smtpHost, smtpPort, senderEmail, enableTLS);
    }
}
```

### 3. AuthServiceConfig.java

```java
package org.appops.amur.config;

public class AuthServiceConfig {
    private String authUrl;
    private int tokenExpiry;
    private String secretKey;

    public AuthServiceConfig() {}

    public String getAuthUrl() { return authUrl; }
    public void setAuthUrl(String authUrl) { this.authUrl = authUrl; }

    public int getTokenExpiry() { return tokenExpiry; }
    public void setTokenExpiry(int tokenExpiry) { this.tokenExpiry = tokenExpiry; }

    public String getSecretKey() { return secretKey; }
    public void setSecretKey(String secretKey) { this.secretKey = secretKey; }

    @Override
    public String toString() {
        return String.format("AuthServiceConfig{authUrl='%s', tokenExpiry=%d}",
                authUrl, tokenExpiry);
    }
}
```

### 4. NotificationConfig.java

```java
package org.appops.amur.config;

public class NotificationConfig {
    private boolean enableEmail;
    private boolean enableSMS;
    private String defaultTemplate;

    public NotificationConfig() {}

    public boolean isEnableEmail() { return enableEmail; }
    public void setEnableEmail(boolean enableEmail) { this.enableEmail = enableEmail; }

    public boolean isEnableSMS() { return enableSMS; }
    public void setEnableSMS(boolean enableSMS) { this.enableSMS = enableSMS; }

    public String getDefaultTemplate() { return defaultTemplate; }
    public void setDefaultTemplate(String defaultTemplate) { this.defaultTemplate = defaultTemplate; }

    @Override
    public String toString() {
        return String.format("NotificationConfig{enableEmail=%s, enableSMS=%s, defaultTemplate='%s'}",
                enableEmail, enableSMS, defaultTemplate);
    }
}
```

### 5. PaymentServiceConfig.java

```java
package org.appops.amur.config;

public class PaymentServiceConfig {
    private String paymentGateway;
    private String apiKey;
    private String webhookSecret;
    private String currency;

    public PaymentServiceConfig() {}

    public String getPaymentGateway() { return paymentGateway; }
    public void setPaymentGateway(String paymentGateway) { this.paymentGateway = paymentGateway; }

    public String getApiKey() { return apiKey; }
    public void setApiKey(String apiKey) { this.apiKey = apiKey; }

    public String getWebhookSecret() { return webhookSecret; }
    public void setWebhookSecret(String webhookSecret) { this.webhookSecret = webhookSecret; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    @Override
    public String toString() {
        return String.format("PaymentServiceConfig{paymentGateway='%s', currency='%s'}",
                paymentGateway, currency);
    }
}
```

### 6. OrderServiceConfig.java

```java
package org.appops.amur.config;

public class OrderServiceConfig {
    private int maxOrderItems;
    private int orderTimeout;
    private boolean autoConfirm;

    public OrderServiceConfig() {}

    public int getMaxOrderItems() { return maxOrderItems; }
    public void setMaxOrderItems(int maxOrderItems) { this.maxOrderItems = maxOrderItems; }

    public int getOrderTimeout() { return orderTimeout; }
    public void setOrderTimeout(int orderTimeout) { this.orderTimeout = orderTimeout; }

    public boolean isAutoConfirm() { return autoConfirm; }
    public void setAutoConfirm(boolean autoConfirm) { this.autoConfirm = autoConfirm; }

    @Override
    public String toString() {
        return String.format("OrderServiceConfig{maxOrderItems=%d, orderTimeout=%d, autoConfirm=%s}",
                maxOrderItems, orderTimeout, autoConfirm);
    }
}
```

## 🔧 Verify Your Project Structure

After creating all files, your project should look like:

```
src/
├── main/
│   ├── java/
│   │   └── org/appops/amur/config/
│   │       ├── ConfigLoader.java
│   │       ├── EnvironmentConfigStore.java
│   │       ├── CoreServiceConfig.java
│   │       ├── SlimServiceConfig.java
│   │       ├── ImplServiceConfig.java
│   │       ├── UserServiceConfig.java
│   │       ├── EmailServiceConfig.java
│   │       ├── AuthServiceConfig.java
│   │       ├── NotificationConfig.java
│   │       ├── PaymentServiceConfig.java
│   │       └── OrderServiceConfig.java
│   └── resources/
│       └── env-config/
│           ├── core.yml
│           ├── TestService/slim.yml
│           ├── HService/slim.yml
│           ├── UserService/slim.yml
│           ├── SomeOtherService/slim.yml
│           └── NirajService/
│               ├── slim.yml
│               └── impl.yml
```

## 🧪 Test Again

After setting up all files, run your test again. You should see:

```
🚀 Testing ConfigLoader with Real Files
=======================================

1️⃣ Testing Core Config:
🔍 Loading config from: /env-config/core.yml
✅ Successfully loaded Core config for Core
✅ Core config stored
✅ Core Config loaded: CoreService

2️⃣ Testing TestService Slim Config:
🔍 Loading config from: /env-config/TestService/slim.yml
✅ Converted UserServiceConfig to typed object
✅ Converted EmailServiceConfig to typed object
✅ Successfully loaded slim config for TestService
✅ TestService Config loaded with 2 nested configs
   ✅ UserServiceConfig converted: http://localhost:8081
```

## ⚡ Quick One-Command Setup

If you want to create all directories at once:

```bash
mkdir -p src/main/resources/env-config/{TestService,HService,UserService,SomeOtherService,NirajService}
```

Then create the YAML files one by one in each directory as shown above!
